package hyx.repository.mybatis.mapper;

import hyx.repository.mybatis.entity.FamilyRelation;
import hyx.repository.mybatis.entity.FamilyRelationExample;
import hyx.repository.mybatis.entity.FamilyRelationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FamilyRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int countByExample(FamilyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int deleteByExample(FamilyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int deleteByPrimaryKey(FamilyRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int insert(FamilyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int insertSelective(FamilyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    List<FamilyRelation> selectByExample(FamilyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    FamilyRelation selectByPrimaryKey(FamilyRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") FamilyRelation record, @Param("example") FamilyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByExample(@Param("record") FamilyRelation record, @Param("example") FamilyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByPrimaryKeySelective(FamilyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByPrimaryKey(FamilyRelation record);
}