package hyx.repository.mybatis.mapper;

import hyx.repository.mybatis.entity.Name;
import hyx.repository.mybatis.entity.NameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int countByExample(NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int deleteByExample(NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int insert(Name record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int insertSelective(Name record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    List<Name> selectByExample(NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    Name selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") Name record, @Param("example") NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByExample(@Param("record") Name record, @Param("example") NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByPrimaryKeySelective(Name record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    int updateByPrimaryKey(Name record);
}