package hyx.repository.mybatis.entity;

public class FamilyRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_relation.relation_type
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    private String relationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_relation.source_id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    private Long sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_relation.target_id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    private Long targetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public FamilyRelationKey(String relationType, Long sourceId, Long targetId) {
        this.relationType = relationType;
        this.sourceId = sourceId;
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public FamilyRelationKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_relation.relation_type
     *
     * @return the value of family_relation.relation_type
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_relation.relation_type
     *
     * @param relationType the value for family_relation.relation_type
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public void setRelationType(String relationType) {
        this.relationType = relationType == null ? null : relationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_relation.source_id
     *
     * @return the value of family_relation.source_id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_relation.source_id
     *
     * @param sourceId the value for family_relation.source_id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_relation.target_id
     *
     * @return the value of family_relation.target_id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_relation.target_id
     *
     * @param targetId the value for family_relation.target_id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }
}