package hyx.repository.mybatis.entity;

public class FamilyRelation extends FamilyRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_relation.description
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public FamilyRelation(String relationType, Long sourceId, Long targetId, String description) {
        super(relationType, sourceId, targetId);
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_relation
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public FamilyRelation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_relation.description
     *
     * @return the value of family_relation.description
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_relation.description
     *
     * @param description the value for family_relation.description
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}