package hyx.repository.mybatis.entity;

public class Name {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name.id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name.name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name.family_name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    private String familyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public Name(Long id, String name, String familyName) {
        this.id = id;
        this.name = name;
        this.familyName = familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public Name() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name.id
     *
     * @return the value of name.id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name.id
     *
     * @param id the value for name.id
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name.name
     *
     * @return the value of name.name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name.name
     *
     * @param name the value for name.name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name.family_name
     *
     * @return the value of name.family_name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name.family_name
     *
     * @param familyName the value for name.family_name
     *
     * @mbggenerated Fri Oct 13 16:59:44 CST 2017
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }
}